mail_settings:
  email: 'contact@nirmalcs.com'
  password: '[tsbom1!'
  host_url: 'pixsume.com'
  
social_apps: 
  linkedin:
    consumer_key: 'sg1vbkahtj8p' #7qqf1hkogdwz
    consumer_secret: 'neOqgKzvF9pZyzlI' #3uAFJWB8AALcTxe4
